<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Core Properties">
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup Label="xUnit v3">
    <PackageReference Include="xunit.v3.mtp-v2" />
    <PackageReference Include="Microsoft.Testing.Platform" />
  </ItemGroup>
  <ItemGroup Label="Testing Infrastructure">
    <PackageReference Include="IndQuestResults" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Shouldly" />
  </ItemGroup>
  <ItemGroup Label="Global Usings">
    <Using Include="IndQuestResults" />
    <Using Include="IndQuestResults.Operations" />
  </ItemGroup>
  <ItemGroup Label="Project References">
    <ProjectReference Include="..\..\..\..\01 Core\Domain\ExxerCube.Prisma.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\04 Services\Orion\Prisma.Orion.HealthChecks\ExxerCube.Prisma.Orion.HealthChecks.csproj" />
  </ItemGroup>
</Project>
