<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
	  <NoWarn>NU1605;1008</NoWarn>
	  <WarningsNotAsErrors>NU1605;1008</WarningsNotAsErrors>

	  <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
	 
	  <PackageReference Include="xunit.runner.visualstudio" >
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Shouldly"  />
    <PackageReference Include="NSubstitute"  />
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="Meziantou.Extensions.Logging.Xunit.v3" />
    <PackageReference Include="StrykerMutator.Core" />
    <PackageReference Include="Microsoft.Playwright" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\ExxerCube.Prisma.Domain.csproj" />
    <ProjectReference Include="..\Application\ExxerCube.Prisma.Application.csproj" />
    <ProjectReference Include="..\Infrastructure\ExxerCube.Prisma.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="TestData\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
