// <auto-generated />
using System;
using ExxerCube.Prisma.Veriqan.Infrastructure.Persistence.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExxerCube.Prisma.Veriqan.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VeriqanDbContext))]
    [Migration("20260617024051_InitialVeriqanSchema")]
    partial class InitialVeriqanSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("veriqan")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExxerCube.Prisma.Veriqan.Domain.Entities.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CheckId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EngineVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Expected")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Observed")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Verdict")
                        .HasColumnType("int");

                    b.Property<Guid>("VerificationJobId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CheckId")
                        .HasDatabaseName("IX_Findings_CheckId");

                    b.HasIndex("VerificationJobId")
                        .HasDatabaseName("IX_Findings_VerificationJobId");

                    b.ToTable("Findings", "veriqan");
                });

            modelBuilder.Entity("ExxerCube.Prisma.Veriqan.Domain.Entities.JobVerdict", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Signal")
                        .HasColumnType("int");

                    b.Property<Guid>("VerificationJobId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VerificationJobId")
                        .IsUnique()
                        .HasDatabaseName("IX_JobVerdicts_VerificationJobId");

                    b.ToTable("JobVerdicts", "veriqan");
                });

            modelBuilder.Entity("ExxerCube.Prisma.Veriqan.Domain.Entities.VerificationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique()
                        .HasDatabaseName("IX_VerificationJobs_ContentHash");

                    b.HasIndex("ReceivedAtUtc")
                        .HasDatabaseName("IX_VerificationJobs_ReceivedAtUtc");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_VerificationJobs_Status");

                    b.ToTable("VerificationJobs", "veriqan");
                });

            modelBuilder.Entity("ExxerCube.Prisma.Veriqan.Domain.Entities.Finding", b =>
                {
                    b.HasOne("ExxerCube.Prisma.Veriqan.Domain.Entities.VerificationJob", null)
                        .WithMany("Findings")
                        .HasForeignKey("VerificationJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExxerCube.Prisma.Veriqan.Domain.Entities.JobVerdict", b =>
                {
                    b.HasOne("ExxerCube.Prisma.Veriqan.Domain.Entities.VerificationJob", null)
                        .WithOne("Verdict")
                        .HasForeignKey("ExxerCube.Prisma.Veriqan.Domain.Entities.JobVerdict", "VerificationJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExxerCube.Prisma.Veriqan.Domain.Entities.VerificationJob", b =>
                {
                    b.Navigation("Findings");

                    b.Navigation("Verdict");
                });
#pragma warning restore 612, 618
        }
    }
}
