// <auto-generated />
using System;
using ExxerCube.Prisma.Veriqan.Infrastructure.Persistence.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExxerCube.Prisma.Veriqan.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VeriqanDbContext))]
    [Migration("20260727233432_AddJobVerdictProvenance")]
    partial class AddJobVerdictProvenance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("veriqan")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExxerCube.Prisma.Veriqan.Domain.Entities.Disposition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AfterState")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("BeforeState")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("DispositionedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EngineVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("FindingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ReferenceBundleVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("VerificationJobId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FindingId")
                        .HasDatabaseName("IX_Dispositions_FindingId");

                    b.HasIndex("VerificationJobId")
                        .HasDatabaseName("IX_Dispositions_VerificationJobId");

                    b.ToTable("Dispositions", "veriqan");
                });

            modelBuilder.Entity("ExxerCube.Prisma.Veriqan.Domain.Entities.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CheckId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double>("Confidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(1.0);

                    b.Property<string>("EngineVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Expected")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Observed")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Tier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("Verdict")
                        .HasColumnType("int");

                    b.Property<Guid>("VerificationJobId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CheckId")
                        .HasDatabaseName("IX_Findings_CheckId");

                    b.HasIndex("VerificationJobId")
                        .HasDatabaseName("IX_Findings_VerificationJobId");

                    b.ToTable("Findings", "veriqan");
                });

            modelBuilder.Entity("ExxerCube.Prisma.Veriqan.Domain.Entities.JobVerdict", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AlertSentAt")
                        .IsConcurrencyToken()
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("BankTierVerdict")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("CondusefTierVerdict")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<double>("Confidence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(1.0);

                    b.Property<string>("EngineVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("unknown");

                    b.Property<string>("ReferenceBundleVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Signal")
                        .HasColumnType("int");

                    b.Property<Guid>("VerificationJobId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VerificationJobId")
                        .IsUnique()
                        .HasDatabaseName("IX_JobVerdicts_VerificationJobId");

                    b.ToTable("JobVerdicts", "veriqan");
                });

            modelBuilder.Entity("ExxerCube.Prisma.Veriqan.Domain.Entities.VerificationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("ReceivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .IsUnique()
                        .HasDatabaseName("IX_VerificationJobs_ContentHash");

                    b.HasIndex("ReceivedAtUtc")
                        .HasDatabaseName("IX_VerificationJobs_ReceivedAtUtc");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_VerificationJobs_Status");

                    b.ToTable("VerificationJobs", "veriqan");
                });

            modelBuilder.Entity("ExxerCube.Prisma.Veriqan.Infrastructure.Persistence.EntityFramework.LegalBaselineToleranceRecord", b =>
                {
                    b.Property<string>("CheckId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LegalDefault")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Max")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Min")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CheckId");

                    b.ToTable("LegalBaselineTolerances", "veriqan");
                });

            modelBuilder.Entity("ExxerCube.Prisma.Veriqan.Infrastructure.Persistence.EntityFramework.ReprocessAuditLogEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("AfterSignal")
                        .HasColumnType("int");

                    b.Property<int?>("BeforeSignal")
                        .HasColumnType("int");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("ReprocessedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash", "ReprocessedAtUtc")
                        .HasDatabaseName("IX_ReprocessAuditLog_ContentHash");

                    b.ToTable("ReprocessAuditLog", "veriqan");
                });

            modelBuilder.Entity("ExxerCube.Prisma.Veriqan.Infrastructure.Persistence.EntityFramework.VerificationOutcomeSnapshotEntity", b =>
                {
                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("OutcomeJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ReplacedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("SavedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ContentHash");

                    b.ToTable("VerificationOutcomeSnapshots", "veriqan");
                });

            modelBuilder.Entity("ExxerCube.Prisma.Veriqan.Domain.Entities.Finding", b =>
                {
                    b.HasOne("ExxerCube.Prisma.Veriqan.Domain.Entities.VerificationJob", null)
                        .WithMany("Findings")
                        .HasForeignKey("VerificationJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExxerCube.Prisma.Veriqan.Domain.Entities.JobVerdict", b =>
                {
                    b.HasOne("ExxerCube.Prisma.Veriqan.Domain.Entities.VerificationJob", null)
                        .WithOne("Verdict")
                        .HasForeignKey("ExxerCube.Prisma.Veriqan.Domain.Entities.JobVerdict", "VerificationJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExxerCube.Prisma.Veriqan.Domain.Entities.VerificationJob", b =>
                {
                    b.Navigation("Findings");

                    b.Navigation("Verdict");
                });
#pragma warning restore 612, 618
        }
    }
}
