<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Core Properties">
    <!-- Target framework centrally managed — do not add another here -->
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup Label="Core Packages">
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="IndQuestResults" />
    <PackageReference Include="Microsoft.Playwright" />
  </ItemGroup>

</Project>
