<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-ExxerCube.Prisma.Web.UI-889a571d-e37b-47ea-b986-9e8601044c7a</UserSecretsId>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" />
    <PackageReference Include="MudBlazor" />
    <PackageReference Include="Extensions.MudBlazor.StaticInput" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Application\ExxerCube.Prisma.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\ExxerCube.Prisma.Infrastructure.csproj" />
  </ItemGroup>

</Project>