// <auto-generated />
using System;
using ExxerCube.Prisma.Infrastructure.Export.Adaptive.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExxerCube.Prisma.Infrastructure.Export.Adaptive.Data.Migrations
{
    [DbContext(typeof(TemplateDbContext))]
    [Migration("20251208013509_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExxerCube.Prisma.Domain.Entities.TemplateDefinition", b =>
                {
                    b.Property<string>("TemplateId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RootElement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("XmlNamespace")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TemplateId");

                    b.HasIndex("TemplateType", "Version")
                        .IsUnique();

                    b.HasIndex("TemplateType", "IsActive", "EffectiveDate");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("ExxerCube.Prisma.Domain.Entities.TemplateDefinition", b =>
                {
                    b.OwnsMany("ExxerCube.Prisma.Domain.ValueObjects.FieldMapping", "FieldMappings", b1 =>
                        {
                            b1.Property<string>("TemplateDefinitionTemplateId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("DataType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("DefaultValue")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("DisplayName")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("DisplayOrder")
                                .HasColumnType("int");

                            b1.Property<string>("Format")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("IsNullable")
                                .HasColumnType("bit");

                            b1.Property<bool>("IsRequired")
                                .HasColumnType("bit");

                            b1.Property<string>("MappingId")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("MaxLength")
                                .HasColumnType("int");

                            b1.Property<string>("SourceFieldPath")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TargetField")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("TransformExpression")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TemplateDefinitionTemplateId", "Id");

                            b1.ToTable("FieldMapping");

                            b1.WithOwner()
                                .HasForeignKey("TemplateDefinitionTemplateId");
                        });

                    b.Navigation("FieldMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
