<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Target framework centrally managed do not add another here -->
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DocumentationFile>$(OutputPath)$(AssemblyName).xml</DocumentationFile>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="IndQuestResults" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
  </ItemGroup>

  <ItemGroup>
    <!-- Core -->
    <ProjectReference Include="..\..\01 Core\Veriqan.Application\ExxerCube.Prisma.Veriqan.Application.csproj" />
    <!-- Infrastructure adapters -->
    <ProjectReference Include="..\..\02 Infrastructure\Veriqan.Infrastructure.Extraction\ExxerCube.Prisma.Veriqan.Infrastructure.Extraction.csproj" />
    <ProjectReference Include="..\..\02 Infrastructure\Veriqan.Infrastructure.Validation\ExxerCube.Prisma.Veriqan.Infrastructure.Validation.csproj" />
    <ProjectReference Include="..\..\02 Infrastructure\Veriqan.Infrastructure.Visual\ExxerCube.Prisma.Veriqan.Infrastructure.Visual.csproj" />
    <ProjectReference Include="..\..\02 Infrastructure\Veriqan.Infrastructure.ReferenceData\ExxerCube.Prisma.Veriqan.Infrastructure.ReferenceData.csproj" />
    <ProjectReference Include="..\..\02 Infrastructure\Veriqan.Infrastructure.Reporting\ExxerCube.Prisma.Veriqan.Infrastructure.Reporting.csproj" />
    <ProjectReference Include="..\..\02 Infrastructure\Veriqan.Infrastructure.Persistence\ExxerCube.Prisma.Veriqan.Infrastructure.Persistence.csproj" />
  </ItemGroup>

</Project>
