<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
   <!-- "Target framework centrally manged do not add another here  -->
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>


    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoWarn>xUnit1051</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="sample.flac" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="sample.flac">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Shouldly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TransformersSharp\TransformersSharp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
