<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Core Properties">
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);xUnit1051</NoWarn>
  </PropertyGroup>
  <ItemGroup Label="xUnit v3">
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Microsoft.Testing.Platform" />
  </ItemGroup>
  <ItemGroup Label="Testing Infrastructure">
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>
  <ItemGroup Label="Project References">
    <ProjectReference Include="..\..\..\..\01 Core\Domain\ExxerCube.Prisma.Domain.csproj" />
    <ProjectReference Include="..\..\..\..\04 Services\Athena\Prisma.Athena.HealthChecks\ExxerCube.Prisma.Athena.HealthChecks.csproj" />
    <ProjectReference Include="..\..\..\..\04 Services\Athena\Prisma.Athena.Processing\ExxerCube.Prisma.Athena.Processing.csproj" />
    <ProjectReference Include="..\..\..\..\04 Services\Athena\Prisma.Athena.Worker\ExxerCube.Prisma.Athena.Worker.csproj" />
  </ItemGroup>
</Project>
