using Microsoft.Extensions.Logging;
using ExxerCube.Prisma.Infrastructure.Python.VecExtraction.DependencyInjection;

namespace ExxerCube.Prisma.ConsoleApp.VecExtractionDemo;

/// <summary>
/// Console demo application for VEC Statement Extraction integration test
/// </summary>
internal class Program
{
    private static async Task<int> Main(string[] args)
    {
        // Configure Serilog early for diagnostics
        var baseDirectory = AppDomain.CurrentDomain.BaseDirectory;
        var logFilePath = Path.Combine(baseDirectory, "logs", "vec-extraction-demo-.log");

        Log.Logger = new LoggerConfiguration()
            .MinimumLevel.Debug()
            .WriteTo.Console(outputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3}] {Message:lj}{NewLine}{Exception}")
            .WriteTo.File(
                logFilePath,
                rollingInterval: RollingInterval.Day,
                outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {Message:lj}{NewLine}{Exception}",
                retainedFileCountLimit: 7)
            .CreateLogger();

        Log.Information("=== ExxerCube.Prisma - VEC Statement Extraction Demo ===");
        Log.Information("Log file: {LogFilePath}", logFilePath);

        try
        {
            // Build host with Python environment
            var builder = Host.CreateApplicationBuilder(args);

            // Setup Python environment for VEC extraction using Infrastructure DI extension
            Log.Information("Base directory: {BaseDirectory}", baseDirectory);

            // Use manual setup configuration (assumes setup_environment_manual.ps1 was run)
            builder.Services.AddVecExtractionPythonEnvironmentManual(baseDirectory);

            // Add Serilog
            builder.Services.AddSerilog(Log.Logger);

            var host = builder.Build();
            var logger = host.Services.GetRequiredService<Microsoft.Extensions.Logging.ILogger<Program>>();
            logger.LogInformation("Is these project really working on??");
            // CSnakes will automatically create venv and install packages on first run
            Log.Information("Initializing Python environment (this may take several minutes on first run)...");
            Log.Information("- Downloading Python 3.13 redistributable if needed");
            Log.Information("- Creating virtual environment");
            Log.Information("- Installing PyTorch, transformers, and VEC processing dependencies");
            Log.Information("- This includes: LayoutLMv3, Table Transformer, CLIP, pdfplumber, etc.");

            // Get Python environment
            var pythonEnv = host.Services.GetRequiredService<IPythonEnvironment>();

            Log.Information("✓ Python environment initialized");

            // Run demos
            await RunHealthCheckDemo(pythonEnv);
            await RunVecExtractionDemo(pythonEnv, logger, args);

            Log.Information("Demo completed successfully");
            return 0;
        }
        catch (Exception ex)
        {
            Log.Fatal(ex, "Fatal error in VEC extraction demo");
            return 1;
        }
        finally
        {
            await Log.CloseAndFlushAsync();
        }
    }

    private static async Task RunHealthCheckDemo(IPythonEnvironment pythonEnv)
    {
        Console.WriteLine("\n--- Health Check ---");

        try
        {
            // Use the strongly-typed interface generated by CSnakes
            var module = pythonEnv.VecCsnakesWrapper();

            // Get version and module info
            var version = module.GetVersion();
            var moduleInfo = module.GetModuleInfo();

            Console.WriteLine($"✓ Module version: {version}");
            Console.WriteLine($"✓ Module info: {moduleInfo}");

            // Run health check
            Console.WriteLine("\nRunning health check...");
            var isHealthy = module.HealthCheck();

            if (isHealthy)
            {
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("✓ Health check PASSED - VEC extraction module loaded successfully");
                Console.ResetColor();
            }
            else
            {
                Console.ForegroundColor = ConsoleColor.Yellow;
                Console.WriteLine("⚠ Health check FAILED");
                Console.ResetColor();
            }
        }
        catch (Exception ex)
        {
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine($"✗ Health check error: {ex.Message}");
            if (ex.InnerException != null)
            {
                Console.WriteLine($"✗ Inner error: {ex.InnerException.Message}");
            }
            Console.ResetColor();
        }

        await Task.CompletedTask;
    }

    private static async Task RunVecExtractionDemo(IPythonEnvironment pythonEnv, Microsoft.Extensions.Logging.ILogger logger, string[] args)
    {
        Console.WriteLine("\n--- VEC Statement Extraction Demo ---");

        // Look for test PDF fixtures
        var fixturesDir = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "test_fixtures");
        string? pdfPath = null;

        if (args.Length > 0 && File.Exists(args[0]))
        {
            pdfPath = args[0];
            Log.Information("Using PDF from command line: {PdfPath}", pdfPath);
        }
        else if (Directory.Exists(fixturesDir))
        {
            var pdfFiles = Directory.GetFiles(fixturesDir, "*.pdf");
            if (pdfFiles.Length > 0)
            {
                pdfPath = pdfFiles[0];
                Log.Information("Using fixture PDF: {PdfPath}", Path.GetFileName(pdfPath));
            }
        }

        if (pdfPath == null)
        {
            Console.WriteLine("\n⚠ Could not locate any VEC PDF files.");
            Console.WriteLine("Usage: dotnet run <pdf-path>");
            Console.WriteLine("       dotnet run \"C:\\path\\to\\vec_statement.pdf\"");
            Console.WriteLine($"\nOr place PDF files in: {fixturesDir}");
            return;
        }

        Log.Information("✓ File located: {FileName}", Path.GetFileName(pdfPath));

        // Read PDF file
        Log.Debug("Reading PDF file: {FilePath}", pdfPath);
        var pdfBytes = await File.ReadAllBytesAsync(pdfPath);
        Log.Debug("PDF size: {Size:N0} bytes", pdfBytes.Length);

        // Get page count for logging
        try
        {
            using var pdfDocument = PdfDocument.Open(pdfBytes);
            Log.Information("PDF contains {PageCount} page(s)", pdfDocument.NumberOfPages);
        }
        catch (Exception ex)
        {
            Log.Warning(ex, "Could not read PDF metadata, will attempt extraction anyway");
        }

        try
        {
            // Use the strongly-typed interface generated by CSnakes
            var module = pythonEnv.VecCsnakesWrapper();

            Log.Information("Extracting VEC statement data (this may take 10-30 seconds)...");
            Log.Information("- Running CLIP logo detection");
            Log.Information("- Running font detection (Aptos compliance)");
            Log.Information("- Running LayoutLMv3 header extraction");
            Log.Information("- Running Table Transformer transaction extraction");

            // Execute VEC extraction with strongly-typed call
            var startTime = DateTime.UtcNow;
            Log.Debug("Starting VEC extraction at {StartTime}", startTime);

            var result = module.ExtractVecStatement(pdfBytes, $"VEC-DEMO-{DateTime.Now:yyyyMMddHHmmss}");

            var elapsed = DateTime.UtcNow - startTime;
            Log.Debug("VEC extraction completed in {Elapsed:F2}s", elapsed.TotalSeconds);

            // Display results
            Console.WriteLine("\n--- Extraction Results ---");

            // Convert dynamic result to dictionary
            var resultDict = (IDictionary<string, object>)result;

            if (resultDict.ContainsKey("success") && (bool)resultDict["success"])
            {
                Log.Information("✓ VEC extraction succeeded");
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine($"✓ SUCCESS - Processing time: {elapsed.TotalSeconds:F2}s");
                Console.ResetColor();

                if (resultDict.ContainsKey("data") && resultDict["data"] != null)
                {
                    var data = (IDictionary<string, object>)resultDict["data"];

                    Console.WriteLine("\nExtracted Information:");
                    Console.WriteLine(new string('-', 80));

                    if (data.ContainsKey("document_id"))
                        Console.WriteLine($"Document ID: {data["document_id"]}");

                    if (data.ContainsKey("total_pages"))
                        Console.WriteLine($"Total Pages: {data["total_pages"]}");

                    if (data.ContainsKey("extraction_confidence"))
                        Console.WriteLine($"Confidence: {data["extraction_confidence"]:F2}");

                    if (data.ContainsKey("model_version"))
                        Console.WriteLine($"Model: {data["model_version"]}");

                    // Header information
                    if (data.ContainsKey("header") && data["header"] != null)
                    {
                        var header = (IDictionary<string, object>)data["header"];
                        Console.WriteLine("\nHeader Fields:");
                        if (header.ContainsKey("account_number"))
                            Console.WriteLine($"  Account: {header["account_number"]}");
                        if (header.ContainsKey("account_holder"))
                            Console.WriteLine($"  Holder: {header["account_holder"]}");
                        if (header.ContainsKey("product_type"))
                            Console.WriteLine($"  Product: {header["product_type"]}");
                        if (header.ContainsKey("final_balance"))
                            Console.WriteLine($"  Balance: ${header["final_balance"]}");
                    }

                    // Transactions
                    if (data.ContainsKey("transactions") && data["transactions"] != null)
                    {
                        var transactions = (System.Collections.IList)data["transactions"];
                        Console.WriteLine($"\nTransactions: {transactions.Count} found");
                    }

                    // Visual compliance
                    Console.WriteLine("\nVisual Compliance:");
                    if (data.ContainsKey("logo_detected"))
                        Console.WriteLine($"  Logo Detected: {(bool)data["logo_detected"]}");
                    if (data.ContainsKey("image_quality_score"))
                        Console.WriteLine($"  Image Quality: {data["image_quality_score"]:F2}");
                    if (data.ContainsKey("font_compliance"))
                        Console.WriteLine($"  Font Compliance: {(bool)data["font_compliance"]}");

                    Console.WriteLine(new string('-', 80));
                }
            }
            else
            {
                var errorMsg = resultDict.ContainsKey("error_message")
                    ? resultDict["error_message"].ToString()
                    : "Unknown error";
                var errorCode = resultDict.ContainsKey("error_code")
                    ? resultDict["error_code"].ToString()
                    : "UNKNOWN";

                Log.Error("✗ VEC extraction failed: [{ErrorCode}] {Error}", errorCode, errorMsg);
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine($"✗ FAILED: [{errorCode}] {errorMsg}");
                Console.ResetColor();
            }
        }
        catch (Exception ex)
        {
            Log.Error(ex, "Exception during VEC extraction");
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine($"✗ Exception: {ex.Message}");
            Console.ResetColor();
        }
    }
}