<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<!-- "Target framework centrally manged do not add another here"  -->
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	<NoWarn>CS1591</NoWarn>

  </PropertyGroup>

  <ItemGroup>
    <None Remove="Python\python\*.py" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="Python\python\*.py" SourceItemType="Python">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </AdditionalFiles>
  </ItemGroup>

  <ItemGroup>
	<PackageReference Include="CSnakes.Runtime" />
	<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
	<PackageReference Include="Microsoft.Extensions.Hosting" />
	<PackageReference Include="Microsoft.Extensions.Logging" />
	<PackageReference Include="Polly" />
	<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
	<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
	<PackageReference Include="System.Drawing.Common" />
	<PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\Domain\ExxerCube.Prisma.Domain.csproj" />
	<ProjectReference Include="..\Application\ExxerCube.Prisma.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Python\Wrappers\" />
  </ItemGroup>

</Project>
