<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net10.0</TargetFramework>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	  <NoWarn>NU1605;1008</NoWarn>
	<!-- CSnakes Configuration -->
	<EmbedPythonSources>true</EmbedPythonSources>
	<DefaultPythonItems>true</DefaultPythonItems>
	<PythonRoot>Python</PythonRoot>
	<WarningsNotAsErrors>NU1605;1008</WarningsNotAsErrors>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="CSnakes.Runtime" />
	<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
	<PackageReference Include="Microsoft.Extensions.Hosting" />
	<PackageReference Include="Microsoft.Extensions.Logging" />
	<PackageReference Include="Polly" />
	<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
	<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
	<PackageReference Include="System.Drawing.Common" />
	<PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\Domain\ExxerCube.Prisma.Domain.csproj" />
	<ProjectReference Include="..\Application\ExxerCube.Prisma.Application.csproj" />
  </ItemGroup>

</Project>
