using System.Text.Json;
using ExxerCube.Prisma.Veriqan.Application.DependencyInjection;
using ExxerCube.Prisma.Veriqan.Application.Ports;
using ExxerCube.Prisma.Veriqan.Domain.Extraction;
using ExxerCube.Prisma.Veriqan.Domain.ReferenceData;
using ExxerCube.Prisma.Veriqan.Infrastructure.Extraction.Ocr;
using ExxerCube.Prisma.Veriqan.Infrastructure.Extraction.Resolution;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging.Abstractions;

namespace ExxerCube.Prisma.Veriqan.Infrastructure.Extraction.Tests;

/// <summary>
/// S7.1 — LiveOcr proof that the production <see cref="HeaderImageOcrStage"/> +
/// <see cref="IProductResolver"/> path recovers the independent synthetic specimen
/// <c>s71-header-ocr-costco</c>'s rasterized header banner and resolves it to the manifest's
/// declared <c>headerOcrProduct</c> identity.
/// </summary>
/// <remarks>
/// <para>
/// This specimen is generated by <c>scripts/veriqan-corpus/synth_gen.py</c>
/// (<c>build_pdf_s71</c>/<c>build_manifest_s71</c>) and is structurally distinct from the demo
/// corpus's <c>good.pdf</c>: it is byte-deterministic, code-generated, and its product banner
/// (<c>"Tarjeta de Crédito COSTCO BANAMEX"</c>) is a raster PNG inserted into the top 30% header
/// band — not a whole-page flatten (contrast <c>build_scanned_doc</c>) — per the shared contract
/// in design doc <c>veriqan-e7-s72-header-ocr-design-2026-07-08.md</c> §4.F.
/// </para>
/// <para>
/// The manifest's expected identity lives in a NEW top-level <c>headerOcrProduct</c> key
/// (<c>productId</c>/<c>productName</c>/<c>assertionRoute</c>), not the <c>fields</c> dict
/// consumed by <see cref="SyntheticGoldenRoundTripTests"/>'s word-geometry
/// <c>[Theory]</c> — <see cref="StatementModelFieldAccessors"/>.Map has no <c>Product</c>
/// accessor, so this is the dedicated resolved-identity assertion route the design doc mandates
/// (<c>"assertionRoute": "resolved-ProductId/LiveOcr"</c>).
/// </para>
/// <para>
/// Runs the real singleton <see cref="TesseractHeaderProductOcrEngine"/>, so this class belongs
/// to <see cref="VeriqanHeaderOcrCollection"/> to serialize with every other test class that
/// constructs it (the native engine deadlocks on a second concurrent instantiation).
/// </para>
/// </remarks>
[Trait("Category", "LiveOcr")]
[Collection(VeriqanHeaderOcrCollection.Name)]
public sealed class SyntheticHeaderOcrProductTests
{
    private static readonly string PdfPath =
        Path.Combine(AppContext.BaseDirectory, "Fixtures", "synthetic", "s71-header-ocr-costco.pdf");

    private static readonly string ManifestPath =
        Path.Combine(AppContext.BaseDirectory, "Fixtures", "synthetic", "s71-header-ocr-costco.manifest.json");

    private static readonly TesseractHeaderProductOcrEngine OcrEngine =
        new(NullLogger<TesseractHeaderProductOcrEngine>.Instance);

    /// <summary>
    /// Drives the production render→crop→OCR→regex path
    /// (<see cref="HeaderImageOcrStage.TryResolveAsync"/>) against the real Tesseract engine over
    /// the synthetic specimen, then resolves the recognized text via the production
    /// <see cref="IProductResolver"/> against a bundle carrying the manifest's declared
    /// <c>headerOcrProduct</c> row, and asserts the resolved <c>ProductId</c> matches.
    /// </summary>
    [Fact]
    public async Task TryResolveAsync_SyntheticHeaderOcrCostcoSpecimen_ResolvesManifestDeclaredProductId()
    {
        var ct = TestContext.Current.CancellationToken;
        if (!File.Exists(PdfPath))
            Assert.Skip($"Synthetic S7.1 fixture not found at: {PdfPath}");
        if (!File.Exists(ManifestPath))
            Assert.Skip($"Synthetic S7.1 manifest not found at: {ManifestPath}");

        var (expectedProductId, expectedProductName) = LoadHeaderOcrProductExpectation(ManifestPath);
        expectedProductId.ShouldNotBeNullOrWhiteSpace(
            "Manifest must declare a headerOcrProduct.productId (design doc §4.F).");
        expectedProductName.ShouldNotBeNullOrWhiteSpace(
            "Manifest must declare a headerOcrProduct.productName (design doc §4.F).");

        var pdfBytes = await File.ReadAllBytesAsync(PdfPath, ct);
        var stage = new HeaderImageOcrStage(OcrEngine, NullLogger<HeaderImageOcrStage>.Instance);

        var context = new FieldResolutionContext<string>(
            FieldKind.Product,
            pdfBytes,
            new LazyPdfCorpus(pdfBytes),
            Array.Empty<FieldCandidate<string>>(),
            new StageBudget());

        var stageResult = await stage.TryResolveAsync(context, ct);

        stageResult.IsSuccess.ShouldBeTrue($"HeaderImageOcrStage failed: {stageResult.Error}");
        var candidate = stageResult.Value!;

        candidate.HasValue.ShouldBeTrue(
            "Real Tesseract OCR over the synthetic S7.1 header crop must recognize the rasterized "
            + "product heading (confirmed GO by the S7.1 make-or-break spike).");
        candidate.Value!.ShouldContain("COSTCO BANAMEX", customMessage: $"Recognized text was: '{candidate.Value}'");
        candidate.Stage.ShouldBe(StageId.HeaderImageOcr);

        // Resolve the recognized text via the PRODUCTION IProductResolver (real DI, never a
        // hand-rolled fake) against a bundle carrying the manifest's declared product row.
        var services = new ServiceCollection();
        services.AddVeriqanBinding();
        using var provider = services.BuildServiceProvider();
        var resolver = provider.GetRequiredService<IProductResolver>();

        var resolveResult = resolver.Resolve(candidate.Value!, BundleWithExpectedProduct(expectedProductId!, expectedProductName!));

        resolveResult.IsSuccess.ShouldBeTrue(
            $"ProductResolver failed to resolve OCR text '{candidate.Value}': {resolveResult.Error}");
        resolveResult.Value!.ProductId.ShouldBe(expectedProductId);
    }

    /// <summary>
    /// Reads the manifest's <c>headerOcrProduct</c> block (design doc §4.F) — the resolved
    /// identity this specimen's OCR read is expected to produce.
    /// </summary>
    private static (string? ProductId, string? ProductName) LoadHeaderOcrProductExpectation(string manifestPath)
    {
        using var doc = JsonDocument.Parse(File.ReadAllText(manifestPath));
        if (!doc.RootElement.TryGetProperty("headerOcrProduct", out var headerOcrProductEl))
            return (null, null);

        var productId = headerOcrProductEl.TryGetProperty("productId", out var idEl) ? idEl.GetString() : null;
        var productName = headerOcrProductEl.TryGetProperty("productName", out var nameEl) ? nameEl.GetString() : null;
        return (productId, productName);
    }

    /// <summary>
    /// Minimal in-memory reference bundle carrying exactly the manifest-declared product row —
    /// this test's job is to gate the OCR-text → regex → resolver PATH against the synthetic
    /// fixture, not to re-verify CSV-catalog-loading machinery (mirrors
    /// <see cref="HeaderImageOcrStageSnapshotTests.DemoCatalogBundle"/>).
    /// </summary>
    private static VecReferenceBundle BundleWithExpectedProduct(string productId, string productName) => new(
        BundleMetadata: new BundleMetadata("1.0.0", "Synthetic S7.1", null, null, null, null),
        Products:
        [
            new VecProduct(
                ProductId: productId,
                ProductName: productName,
                Aliases: [productName],
                HasRewardsProgram: false,
                CardImage: null,
                ImportantMessageImage: null,
                Tariffs: null),
        ],
        InterestRates: null,
        MandatoryLegends: null,
        SequentialImages: null,
        Promotions: null,
        ClientAccounts: null,
        PriorStatements: null,
        ExpectedTransactions: null,
        ToleranceConfig: null,
        ValidationConstants: null);
}
