using CSnakes.Runtime;
using ExxerCube.Prisma.Domain.Interfaces;
using ExxerCube.Prisma.Domain.Models;
using ExxerCube.Prisma.Domain.ValueObjects;
using ExxerCube.Prisma.Infrastructure.Extraction.GotOcr2;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Logging;

namespace ExxerCube.Prisma.ConsoleApp.GotOcr2Demo;

/// <summary>
/// Console demo application for GOT-OCR2 OCR executor integration test
/// </summary>
internal class Program
{
    private static async Task<int> Main(string[] args)
    {
        Console.WriteLine("=== ExxerCube.Prisma - GOT-OCR2 Integration Demo ===\n");

        try
        {
            // Build host with Python environment
            var builder = Host.CreateApplicationBuilder(args);

            // Setup Python environment for GOT-OCR2
            var pythonLibPath = Path.Combine(
                AppDomain.CurrentDomain.BaseDirectory,
                "..", "..", "..", "..", "Infrastructure.Python.GotOcr2"
            );
            pythonLibPath = Path.GetFullPath(pythonLibPath);

            Console.WriteLine($"Python library path: {pythonLibPath}");

            var venvPath = Path.Combine(pythonLibPath, ".venv_gotor2");

            // Configure CSnakes Python environment
            builder.Services
                .WithPython()
                .WithHome(pythonLibPath)
                .WithVirtualEnvironment(venvPath, ensureEnvironment: true)
                .FromRedistributable("3.13")
                .WithPipInstaller("requirements.txt");

            // Add logging
            builder.Logging.ClearProviders();
            builder.Logging.AddConsole();
            builder.Logging.SetMinimumLevel(LogLevel.Information);

            // Register OCR executor
            builder.Services.AddScoped<IOcrExecutor, GotOcr2OcrExecutor>();

            var host = builder.Build();

            // Install Python packages from requirements.txt
            Console.WriteLine("Installing Python dependencies (this may take several minutes on first run)...");
            var packageInstaller = host.Services.GetRequiredService<CSnakes.Runtime.PackageManagement.IPythonPackageInstaller>();
            await packageInstaller.InstallPackagesFromRequirements(pythonLibPath, "requirements.txt");
            Console.WriteLine("✓ Python dependencies installed\n");

            // Get services
            var pythonEnv = host.Services.GetRequiredService<IPythonEnvironment>();
            var executor = host.Services.GetRequiredService<IOcrExecutor>();

            // Run demos
            await RunHealthCheckDemo(pythonEnv);
            await RunOcrDemo(executor, args);

            return 0;
        }
        catch (Exception ex)
        {
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine($"\n[ERROR] {ex.Message}");
            Console.ResetColor();
            Console.WriteLine($"\nStack trace:\n{ex.StackTrace}");
            if (ex.InnerException != null)
            {
                Console.WriteLine($"\nInner exception: {ex.InnerException.Message}");
                Console.WriteLine($"Inner stack trace:\n{ex.InnerException.StackTrace}");
            }
            return 1;
        }
    }

    private static async Task RunHealthCheckDemo(IPythonEnvironment pythonEnv)
    {
        Console.WriteLine("\n--- Health Check ---");

        try
        {
            // Use the strongly-typed interface generated by CSnakes
            var module = pythonEnv.GotOcr2Wrapper();

            // Get version and model info
            var version = module.GetVersion();
            var modelInfo = module.GetModelInfo();

            Console.WriteLine($"✓ Module version: {version}");
            Console.WriteLine($"✓ Model info: {modelInfo}");

            // Run health check
            Console.WriteLine("\nRunning health check (this will download GOT-OCR2 model on first run ~3-5GB)...");
            var isHealthy = module.HealthCheck();

            if (isHealthy)
            {
                Console.ForegroundColor = ConsoleColor.Green;
                Console.WriteLine("✓ Health check PASSED - GOT-OCR2 model loaded successfully");
                Console.ResetColor();
            }
            else
            {
                Console.ForegroundColor = ConsoleColor.Yellow;
                Console.WriteLine("⚠ Health check FAILED");
                Console.ResetColor();
            }
        }
        catch (Exception ex)
        {
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine($"✗ Health check error: {ex.Message}");
            if (ex.InnerException != null)
            {
                Console.WriteLine($"✗ Inner error: {ex.InnerException.Message}");
            }
            Console.ResetColor();
        }
    }

    private static async Task RunOcrDemo(IOcrExecutor executor, string[] args)
    {
        Console.WriteLine("\n--- OCR Execution Demo ---");

        // Get image path from args or use default
        string imagePath;

        if (args.Length > 0 && File.Exists(args[0]))
        {
            imagePath = args[0];
        }
        else
        {
            // Look for fixtures in solution
            var fixturesPath = Path.Combine(
                AppDomain.CurrentDomain.BaseDirectory,
                "..", "..", "..", "..", "..", "..", "..", "Fixtures", "PRP1"
            );
            fixturesPath = Path.GetFullPath(fixturesPath);

            if (!Directory.Exists(fixturesPath))
            {
                Console.WriteLine($"\n⚠ Fixtures directory not found: {fixturesPath}");
                Console.WriteLine("Usage: dotnet run <image-path>");
                Console.WriteLine("       dotnet run path/to/document.jpg");
                return;
            }

            var jpgFiles = Directory.GetFiles(fixturesPath, "*.jpg", SearchOption.TopDirectoryOnly);

            if (jpgFiles.Length == 0)
            {
                Console.WriteLine("\n⚠ No image file specified and no fixtures found.");
                Console.WriteLine("Usage: dotnet run <image-path>");
                return;
            }

            imagePath = jpgFiles[0];
        }

        Console.WriteLine($"\nProcessing image: {Path.GetFileName(imagePath)}");

        // Read image
        var imageBytes = await File.ReadAllBytesAsync(imagePath);
        var imageData = new ImageData(imageBytes, imagePath);

        // Configure OCR (Spanish with moderate confidence threshold)
        var config = new OCRConfig(
            language: "spa",
            oem: 1,
            psm: 6,
            fallbackLanguage: "eng",
            confidenceThreshold: 0.7f
        );

        Console.WriteLine($"Running OCR with language={config.Language}, threshold={config.ConfidenceThreshold}...\n");

        // Execute OCR
        var startTime = DateTime.UtcNow;
        var result = await executor.ExecuteOcrAsync(imageData, config);
        var elapsed = DateTime.UtcNow - startTime;

        // Display results
        if (result.IsSuccess)
        {
            var ocrResult = result.Value;

            Console.ForegroundColor = ConsoleColor.Green;
            Console.WriteLine("✓ OCR succeeded");
            Console.ResetColor();

            Console.WriteLine($"\nResults:");
            Console.WriteLine($"  Text length: {ocrResult?.Text.Length ?? 0} characters");
            Console.WriteLine($"  Confidence avg: {ocrResult?.ConfidenceAvg:F2}%");
            Console.WriteLine($"  Confidence median: {ocrResult?.ConfidenceMedian:F2}%");
            Console.WriteLine($"  Language: {ocrResult?.LanguageUsed}");
            Console.WriteLine($"  Processing time: {elapsed.TotalSeconds:F2}s");

            Console.WriteLine($"\nExtracted text (first 500 chars):");
            Console.WriteLine(new string('-', 80));
            var preview = ocrResult?.Text.Length > 500
                ? ocrResult.Text.Substring(0, 500) + "..."
                : ocrResult?.Text;
            Console.WriteLine(preview);
            Console.WriteLine(new string('-', 80));
        }
        else
        {
            Console.ForegroundColor = ConsoleColor.Red;
            Console.WriteLine($"✗ OCR failed: {result.Error}");
            Console.ResetColor();
        }
    }
}
